const GOOGLE_ACCESS_TOKEN_HEADER_NAME: string = "GAT";
const GOOGLE_REFRESH_TOKEN_HEADER_NAME: string = "GRT";
const GOOGLE_EXPIRY_TIMESTAMP_HEADER_NAME: string = "GExpT";

export {
	GOOGLE_ACCESS_TOKEN_HEADER_NAME,
	GOOGLE_REFRESH_TOKEN_HEADER_NAME,
	GOOGLE_EXPIRY_TIMESTAMP_HEADER_NAME,
};
