name: Build the impoexpo website

on: [push, workflow_dispatch]

jobs:
  build:
      runs-on: ubuntu-latest
      environment: production
      steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.11.1
      - name: Setup node.js
        run: pnpm env use --global lts
      - name: Install dependencies
        run: pnpm i
      - name: Build @impoexpo/client
        run: |
          echo "${{ secrets.ENVIRONMENT }}" > ./packages/impoexpo-client/.env
          pnpm run --filter @impoexpo/client build
      - name: Upload the dist folder
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dist
          path: packages/impoexpo-client/dist
